# Generated by Django 2.1.1 on 2019-01-10 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.DecimalField(decimal_places=4, max_digits=5)),
                ('top', models.DecimalField(decimal_places=4, max_digits=5)),
                ('right', models.DecimalField(decimal_places=4, max_digits=5)),
                ('bottom', models.DecimalField(decimal_places=4, max_digits=5)),
                ('anchor_image', models.ImageField(upload_to='anchor')),
            ],
        ),
        migrations.CreateModel(
            name='AnchorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.DecimalField(decimal_places=4, max_digits=5)),
                ('top', models.DecimalField(decimal_places=4, max_digits=5)),
                ('right', models.DecimalField(decimal_places=4, max_digits=5)),
                ('bottom', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes_from_anchor', to='Sean_boxing.Anchor')),
            ],
        ),
        migrations.CreateModel(
            name='BoxTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='Sean_boxing.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OCRSearchRequest_id', models.CharField(max_length=100)),
                ('image_key', models.UUIDField()),
                ('rotation_angle', models.IntegerField(blank=True, null=True)),
                ('rotated_image', models.ImageField(upload_to='rotated_image')),
            ],
        ),
        migrations.CreateModel(
            name='QBQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QBaseQuestion_id', models.IntegerField()),
                ('image_url', models.URLField()),
                ('book_title', models.CharField(max_length=50)),
                ('book_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='QBQ_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='Sean_boxing.QBQ'),
        ),
        migrations.AddField(
            model_name='box',
            name='candidate_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes_from_candi', to='Sean_boxing.Candidates'),
        ),
        migrations.AddField(
            model_name='box',
            name='work_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worked_box', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anchor',
            name='QBQ_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchor', to='Sean_boxing.QBQ'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='anchor_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchors', to='Sean_boxing.AnchorGroup'),
        ),
        migrations.AddField(
            model_name='anchor',
            name='work_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worked_anchor', to=settings.AUTH_USER_MODEL),
        ),
    ]
