# Generated by Django 2.1.1 on 2019-01-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sean_boxing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_candidate_id', models.IntegerField(blank=True, null=True)),
                ('valid', models.NullBooleanField(default=False)),
                ('anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchor_tag', to='Sean_boxing.Anchor')),
            ],
        ),
    ]
