# Generated by Django 2.1.1 on 2019-01-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sean_boxing', '0002_anchortag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anchortag',
            name='used_candidate_id',
        ),
        migrations.AddField(
            model_name='anchortag',
            name='used_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchor_tag_from_candidate', to='Sean_boxing.Candidates'),
        ),
    ]
