# Generated by Django 2.1.1 on 2019-01-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sean_boxing', '0003_auto_20190111_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.NullBooleanField(default=False)),
                ('anchor_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_from_anchor', to='Sean_boxing.Anchor')),
            ],
        ),
        migrations.RemoveField(
            model_name='anchortag',
            name='anchor',
        ),
        migrations.RemoveField(
            model_name='anchortag',
            name='used_candidate',
        ),
        migrations.RemoveField(
            model_name='box',
            name='anchor_source',
        ),
        migrations.RemoveField(
            model_name='box',
            name='candidate_source',
        ),
        migrations.RenameModel(
            old_name='Candidates',
            new_name='CandidateInfo',
        ),
        migrations.DeleteModel(
            name='AnchorTag',
        ),
        migrations.AddField(
            model_name='frame',
            name='candidate_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_from_candidate', to='Sean_boxing.CandidateInfo'),
        ),
        migrations.AddField(
            model_name='box',
            name='frame_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='box_from_frame', to='Sean_boxing.Frame'),
            preserve_default=False,
        ),
    ]
