# Generated by Django 2.1.1 on 2019-01-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sean_boxing', '0008_auto_20190121_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
