# Generated by Django 2.1.1 on 2019-01-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sean_boxing', '0009_auto_20190121_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='valid',
            field=models.NullBooleanField(),
        ),
    ]
