# Generated by Django 2.1.1 on 2019-01-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sean_boxing', '0010_project_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='valid_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
